name: folivora_sizer
description: A new Flutter plugin project.
version: 0.0.1
repository: "https://github.com/Doohyeon-Kim/folivora-sizer.git"


environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.folivora.folivora_sizer
        pluginClass: FolivoraSizerPlugin
      ios:
        pluginClass: FolivoraSizerPlugin
      linux:
        pluginClass: FolivoraSizerPlugin
      macos:
        pluginClass: FolivoraSizerPlugin
      windows:
        pluginClass: FolivoraSizerPluginCApi
      web:
        pluginClass: FolivoraSizerWeb
        fileName: folivora_sizer_web.dart
